version: "3"

services:
  web:
    build: .
    command: bash -c "pip install django==2.0 && python manage.py runsslserver 0.0.0.0:443"
    volumes:
      - .:/usr/src/app
    ports:
      - "443:443"
